os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=unifem/fenics-desktop:latest
    - BRANCH=debug

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e image -e WELCOME)" ]] ||
    (docker build --tag unifem/mapper-desktop:${BRANCH} . &&
     docker push unifem/mapper-desktop:${BRANCH} &&
     touch success)'
  # Test startup scripts
  - './mapper_desktop.py -d -n -t ${BRANCH} && docker stop $(docker ps -q) &&
     ./mapper_jupyter.py -d -n -t ${BRANCH} && docker stop $(docker ps -q)'
  - docker images
